CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(40) NOT NULL,
    lastname VARCHAR(40) NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE roles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    role_name VARCHAR(255) NOT NULL
);

CREATE TABLE tokens (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    revoke_token BOOLEAN NOT NULL DEFAULT false,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT REFERENCES users(id)
);